# Data loading

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
folder ="Resumes"
doc_files=[]
docx_files=[]

In [3]:
all_files= list(Path(folder).rglob('*.doc'))
for file in all_files:
    doc_files.append(file)

In [4]:
len(all_files)

26

In [5]:
for paths in Path(folder).rglob('*.docx'):
    docx_files.append(paths)

In [6]:
files = doc_files+docx_files
print(len(doc_files),len(docx_files),len(files))

26 52 78


In [7]:
docx_files

[WindowsPath('Resumes/Resumes/Internship_Ravali_Musquare Technologies (1).docx'),
 WindowsPath('Resumes/Resumes/Internship_Susovan Bag_Musquare Technologies.docx'),
 WindowsPath('Resumes/Resumes/React Developer_Deepakreddy.docx'),
 WindowsPath('Resumes/Resumes/React Developer_Haripriya.docx'),
 WindowsPath('Resumes/Resumes/React Developer_Kamalakar Reddy.docx'),
 WindowsPath('Resumes/Resumes/React Developer_Naveen sadhu.docx'),
 WindowsPath('Resumes/Resumes/React Developer_Pragnya.docx'),
 WindowsPath('Resumes/Resumes/React Developer_Sarala Madasu-converted.docx'),
 WindowsPath('Resumes/Resumes/React Developer_Thirupathiamma.docx'),
 WindowsPath('Resumes/Resumes/React Dev_Krishna Kanth.docx'),
 WindowsPath('Resumes/Resumes/React Dev_Krishna Kanth_Musquare Technologies.docx'),
 WindowsPath('Resumes/Resumes/React JS Developer_KotaniDurgaprasad[3_1] (1)-converted.docx'),
 WindowsPath('Resumes/Resumes/React JS Developer_Venkatalakshmi (1)-converted.docx'),
 WindowsPath('Resumes/Resumes/Rea

In [8]:
str(doc_files[5]).split("\\")[2]

'Peoplesoft resumes'

In [19]:
import docx
data=[]
category=[]
for i,j in enumerate(docx_files):
    stg=''
# Open the .docx file
    doc = docx.Document(j)

    # Read the paragraphs
    for para in doc.paragraphs:
        stg+=para.text
    data.append(stg)
    category.append(str(docx_files[i]).split("\\")[2])

In [20]:
data

['Name: Ravali P                                                                              Curriculum Vitae                                           Specialization: BE (computer science and Engg)    To utilize my technical skills for achieving the target and developing the best performance in organization.     \t  MANUAL TESTING SKILLS     Strong knowledge in SDLC concepts.    Extensive knowledge in White Box Testing.    Good knowledge in Functional testing, Integration testing,    Extreme Knowledge on System Testing    Good knowledge in Adhoc Testing, Reliability testing.    Good Knowledge on Exploratory Testing    Good knowledge in STLC concepts.    Good knowledge in Test cases and Test scenarios.    Good knowledge in globalization testing, compatibility testing.    Through Knowledge on Regression Testing    Good  knowledge in Test plan.         AGILE METHDOLOGY     Good knowledge on Scrum Methodology.    Expertise in Sprint Planning Meeting.    Good knowledge on Scrum Meeting   

In [21]:
category

['Internship_Ravali_Musquare Technologies (1).docx',
 'Internship_Susovan Bag_Musquare Technologies.docx',
 'React Developer_Deepakreddy.docx',
 'React Developer_Haripriya.docx',
 'React Developer_Kamalakar Reddy.docx',
 'React Developer_Naveen sadhu.docx',
 'React Developer_Pragnya.docx',
 'React Developer_Sarala Madasu-converted.docx',
 'React Developer_Thirupathiamma.docx',
 'React Dev_Krishna Kanth.docx',
 'React Dev_Krishna Kanth_Musquare Technologies.docx',
 'React JS Developer_KotaniDurgaprasad[3_1] (1)-converted.docx',
 'React JS Developer_Venkatalakshmi (1)-converted.docx',
 'Reactjs Developer_kambala sai surendra_Musquare Technologies.docx',
 'Reactjs Developer_M Lokesh Babu_Musquare Technologies.docx',
 'Reactjs Developer_M Lokesh.docx',
 'Reactjs Developer_MD Khizaruddin Rauf _Musquare Technologies.docx',
 'Reactjs Developer_Pranish Sonone_Musquare Technologies.docx',
 'Reactjs Developer_Ranga Gaganam_Musquare Technologies.docx',
 'Reactjs Developer_Shaik Abdul Sharuk_Musqu

In [22]:
import win32com.client as win32
import os
def read_doc(file_path):
    file_path = os.path.abspath(file_path)
    word = win32.gencache.EnsureDispatch('Word.Application')
    doc = word.Documents.Open(file_path)
    doc_text = doc.Content.Text
    doc.Close()
    word.Quit()
    return doc_text

In [23]:
for i,j in enumerate(doc_files):
    try:
        content = read_doc(j)
        if content:  # Check if content is not None
            data.append(content)
            category.append(str(doc_files[i]).split("\\")[2])
    except Exception as e:
        print(f"Failed to read {i}: {e}")

Failed to read 1: This COM object can not automate the makepy process - please run makepy manually for this object
Failed to read 23: (-2147023174, 'The RPC server is unavailable.', None, None)


In [24]:
print(len(data))
print(len(category))

76
76


# Data cleaning and preprocessing

In [25]:
linebreak_removed=[]
for i in data:
    cleaned = i.replace("\n","").replace("\t","").replace("   ","")
    linebreak_removed.append(cleaned)

In [26]:
linebreak_removed

['Name: Ravali PCurriculum Vitae Specialization: BE (computer science and Engg) To utilize my technical skills for achieving the target and developing the best performance in organization. MANUAL TESTING SKILLS  Strong knowledge in SDLC concepts. Extensive knowledge in White Box Testing. Good knowledge in Functional testing, Integration testing, Extreme Knowledge on System Testing Good knowledge in Adhoc Testing, Reliability testing. Good Knowledge on Exploratory Testing Good knowledge in STLC concepts. Good knowledge in Test cases and Test scenarios. Good knowledge in globalization testing, compatibility testing. Through Knowledge on Regression Testing Good  knowledge in Test plan.AGILE METHDOLOGY  Good knowledge on Scrum Methodology. Expertise in Sprint Planning Meeting. Good knowledge on Scrum Meeting Extreme knowledge on Sprint Retrospective Meeting Good knowledge on Product Backlog Meeting and Bug Triage Meeting. Extreme Knowledge on Normalization JAVA SKILLS  Good knowledge on Me

In [27]:
semi_cleaned=[]
for i in linebreak_removed:
    cleaned = i.replace("\r","").replace("\xa0","").replace(".","").replace(":","")
    semi_cleaned.append(cleaned)

In [28]:
semi_cleaned

['Name Ravali PCurriculum Vitae Specialization BE (computer science and Engg) To utilize my technical skills for achieving the target and developing the best performance in organization MANUAL TESTING SKILLS  Strong knowledge in SDLC concepts Extensive knowledge in White Box Testing Good knowledge in Functional testing, Integration testing, Extreme Knowledge on System Testing Good knowledge in Adhoc Testing, Reliability testing Good Knowledge on Exploratory Testing Good knowledge in STLC concepts Good knowledge in Test cases and Test scenarios Good knowledge in globalization testing, compatibility testing Through Knowledge on Regression Testing Good  knowledge in Test planAGILE METHDOLOGY  Good knowledge on Scrum Methodology Expertise in Sprint Planning Meeting Good knowledge on Scrum Meeting Extreme knowledge on Sprint Retrospective Meeting Good knowledge on Product Backlog Meeting and Bug Triage Meeting Extreme Knowledge on Normalization JAVA SKILLS  Good knowledge on Method Overload

In [62]:
df = pd.DataFrame(
    {"Details":semi_cleaned,
     "Type_of_resume":category}
)

In [63]:
df.head()

Details  \
0  Name Ravali PCurriculum Vitae Specialization B...   
1    SUSOVAN  BAGSeeking  a  challenging  positio...   
2  Kanumuru Deepak ReddyCAREER OBJECTIVETo secure...   
3  HARIPRIYA BATTINA Experience as UI Developer i...   
4  KAMALAKAR REDDY A Linked In https//wwwlinkedin...   

                                      Type_of_resume  
0   Internship_Ravali_Musquare Technologies (1).docx  
1  Internship_Susovan Bag_Musquare Technologies.docx  
2                   React Developer_Deepakreddy.docx  
3                     React Developer_Haripriya.docx  
4               React Developer_Kamalakar Reddy.docx

In [64]:
df["Type_of_resume"][0]="React Developer"
df["Type_of_resume"][1]="React Developer"

In [65]:
df.head()

Details  \
0  Name Ravali PCurriculum Vitae Specialization B...   
1    SUSOVAN  BAGSeeking  a  challenging  positio...   
2  Kanumuru Deepak ReddyCAREER OBJECTIVETo secure...   
3  HARIPRIYA BATTINA Experience as UI Developer i...   
4  KAMALAKAR REDDY A Linked In https//wwwlinkedin...   

                         Type_of_resume  
0                       React Developer  
1                       React Developer  
2      React Developer_Deepakreddy.docx  
3        React Developer_Haripriya.docx  
4  React Developer_Kamalakar Reddy.docx

In [66]:
for i in range(len(list(df["Type_of_resume"]))):
    df["Type_of_resume"][i]=str(df["Type_of_resume"][i]).split("_")[0]

In [67]:
df["Type_of_resume"]

0     React Developer
1     React Developer
2     React Developer
3     React Developer
4     React Developer
           ...       
71    workday resumes
72    workday resumes
73    workday resumes
74    workday resumes
75    workday resumes
Name: Type_of_resume, Length: 76, dtype: object

In [68]:
X=df

In [69]:
import re
X["cleaned_data"]=0
for i in range(len(list(X["Details"]))):
    X["cleaned_data"][i]=re.sub("[^a-zA-Z0-9\s]","",str(X["Details"][i])
)

C:\Users\sumen\AppData\Local\Temp\ipykernel_3404\1211738214.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["cleaned_data"][i]=re.sub("[^a-zA-Z0-9\s]","",str(X["Details"][i])


In [70]:
X.head()

Details   Type_of_resume  \
0  Name Ravali PCurriculum Vitae Specialization B...  React Developer   
1    SUSOVAN  BAGSeeking  a  challenging  positio...  React Developer   
2  Kanumuru Deepak ReddyCAREER OBJECTIVETo secure...  React Developer   
3  HARIPRIYA BATTINA Experience as UI Developer i...  React Developer   
4  KAMALAKAR REDDY A Linked In https//wwwlinkedin...  React Developer   

                                        cleaned_data  
0  Name Ravali PCurriculum Vitae Specialization B...  
1    SUSOVAN  BAGSeeking  a  challenging  positio...  
2  Kanumuru Deepak ReddyCAREER OBJECTIVETo secure...  
3  HARIPRIYA BATTINA Experience as UI Developer i...  
4  KAMALAKAR REDDY A Linked In httpswwwlinkedinco...

In [71]:
df["Details"][0]

'Name Ravali PCurriculum Vitae Specialization BE (computer science and Engg) To utilize my technical skills for achieving the target and developing the best performance in organization MANUAL TESTING SKILLS  Strong knowledge in SDLC concepts Extensive knowledge in White Box Testing Good knowledge in Functional testing, Integration testing, Extreme Knowledge on System Testing Good knowledge in Adhoc Testing, Reliability testing Good Knowledge on Exploratory Testing Good knowledge in STLC concepts Good knowledge in Test cases and Test scenarios Good knowledge in globalization testing, compatibility testing Through Knowledge on Regression Testing Good  knowledge in Test planAGILE METHDOLOGY  Good knowledge on Scrum Methodology Expertise in Sprint Planning Meeting Good knowledge on Scrum Meeting Extreme knowledge on Sprint Retrospective Meeting Good knowledge on Product Backlog Meeting and Bug Triage Meeting Extreme Knowledge on Normalization JAVA SKILLS  Good knowledge on Method Overloadi

In [72]:
X["cleaned_data"][0]

'Name Ravali PCurriculum Vitae Specialization BE computer science and Engg To utilize my technical skills for achieving the target and developing the best performance in organization MANUAL TESTING SKILLS  Strong knowledge in SDLC concepts Extensive knowledge in White Box Testing Good knowledge in Functional testing Integration testing Extreme Knowledge on System Testing Good knowledge in Adhoc Testing Reliability testing Good Knowledge on Exploratory Testing Good knowledge in STLC concepts Good knowledge in Test cases and Test scenarios Good knowledge in globalization testing compatibility testing Through Knowledge on Regression Testing Good  knowledge in Test planAGILE METHDOLOGY  Good knowledge on Scrum Methodology Expertise in Sprint Planning Meeting Good knowledge on Scrum Meeting Extreme knowledge on Sprint Retrospective Meeting Good knowledge on Product Backlog Meeting and Bug Triage Meeting Extreme Knowledge on Normalization JAVA SKILLS  Good knowledge on Method Overloading and

In [73]:
from sklearn.preprocessing import LabelEncoder
encdr= LabelEncoder()

In [74]:
df["Type_of_resume"].unique()

array(['React Developer', 'React Dev', 'React JS Developer',
       'Reactjs Developer', 'Peoplesoft resumes',
       'SQL Developer Lightning insight', 'workday resumes'], dtype=object)

In [75]:
for i in range(len(list(df["Type_of_resume"]))):
    if str(df["Type_of_resume"][i]).startswith("React"):
        df["Type_of_resume"][i]="React Developer"

In [76]:
df["Type_of_resume"].unique()

array(['React Developer', 'Peoplesoft resumes',
       'SQL Developer Lightning insight', 'workday resumes'], dtype=object)

In [77]:
df["Type_of_resume"]=encdr.fit_transform(df["Type_of_resume"])

In [78]:
df["Type_of_resume"].unique()

array([1, 0, 2, 3])

In [81]:
df["Type_of_resume"].value_counts()

Type_of_resume
1    22
0    20
3    20
2    14
Name: count, dtype: int64

In [85]:
import re
df["cleaned_data"]=0
for i in range(len(list(df["Details"]))):
    df["cleaned_data"][i]=re.sub("[^a-zA-Z0-9\s]","",str(df["Details"][i])
)

C:\Users\sumen\AppData\Local\Temp\ipykernel_3404\4064938084.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["cleaned_data"][i]=re.sub("[^a-zA-Z0-9\s]","",str(df["Details"][i])


In [87]:
df = df.drop_duplicates()

In [88]:
df

Details  Type_of_resume  \
0   Name Ravali PCurriculum Vitae Specialization B...               1   
1     SUSOVAN  BAGSeeking  a  challenging  positio...               1   
2   Kanumuru Deepak ReddyCAREER OBJECTIVETo secure...               1   
3   HARIPRIYA BATTINA Experience as UI Developer i...               1   
4   KAMALAKAR REDDY A Linked In https//wwwlinkedin...               1   
..                                                ...             ...   
71  Madeeswar APROFILE SUMMARYHaving around 6 year...               3   
72  Name Naresh Babu CherukuriObjectiveTo take up ...               3   
73  33 years of IT experience as Workday HCM T...               3   
74  Workday Integration ConsultantName Sri Krishna...               3   
75  VenkateswarluBWorkday Consultant   Having 53 y...               3   

                                         cleaned_data  
0   Name Ravali PCurriculum Vitae Specialization B...  
1     SUSOVAN  BAGSeeking  a  challenging  positio...  
2   Kanumuru Deepak ReddyCAREER OBJECTIVETo secure...  
3   HARIPRIYA BATTINA Experience as UI Developer i...  
4   KAMALAKAR REDDY A Linked In httpswwwlinkedinco...  
..                                                ...  
71  Madeeswar APROFILE SUMMARYHaving around 6 year...  
72  Name Naresh Babu CherukuriObjectiveTo take up ...  
73  33 years of IT experience as Workday HCM Techn...  
74  Workday Integration ConsultantName Sri Krishna...  
75  VenkateswarluBWorkday Consultant   Having 53 y...  

[74 rows x 3 columns]

In [95]:
#stemming the data (reducing it to its root word)
import nltk
from nltk.stem import PorterStemmer
corpus=[]
stemmer = PorterStemmer()
for i in df["cleaned_data"]:
    sent = i
    words = sent.split()
    words = [stemmer.stem(word) for word in words]
    sent = " ".join(words)
    corpus.append(sent)

In [96]:
corpus

['name ravali pcurriculum vita special be comput scienc and engg to util my technic skill for achiev the target and develop the best perform in organ manual test skill strong knowledg in sdlc concept extens knowledg in white box test good knowledg in function test integr test extrem knowledg on system test good knowledg in adhoc test reliabl test good knowledg on exploratori test good knowledg in stlc concept good knowledg in test case and test scenario good knowledg in global test compat test through knowledg on regress test good knowledg in test planagil methdolog good knowledg on scrum methodolog expertis in sprint plan meet good knowledg on scrum meet extrem knowledg on sprint retrospect meet good knowledg on product backlog meet and bug triag meet extrem knowledg on normal java skill good knowledg on method overload and method overrid good understand on static and nonstat good understand on variabl good knowledg on constructor good knowledg in abstract good knowledg in encapsul go

# Model training

In [97]:
#vectorizing the text data
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=4000)
X = cv.fit_transform(corpus).toarray()

In [100]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [99]:
Y= np.array(df["Type_of_resume"])

In [101]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, random_state=17)

In [102]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier,RandomForestClassifier
from sklearn.impute import KNNImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import RidgeClassifier
from sklearn.preprocessing import StandardScaler,RobustScaler,MinMaxScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import confusion_matrix,classification_report

In [103]:
def model_performance(preprocessor,xtrain,xtest,ytrain,ytest):
    models={
        'DecisionTreeClassifier':DecisionTreeClassifier(),
        'GaussianNB':GaussianNB(),
        'GradientBoostingClassifier':GradientBoostingClassifier(),
        ' ':RandomForestClassifier(),
        'SVC':SVC(),
        'KNeighborsClassifier':KNeighborsClassifier(),
        'RidgeClassifier': RidgeClassifier()
    }
    for name,model in models.items():
        pipeline=make_pipeline(preprocessor,model)
        pipeline.fit(xtrain,ytrain)
        ypred=pipeline.predict(xtest)

        #checking the metrics of model

        matrix=confusion_matrix(ytest,ypred)
        report=classification_report(ytest,ypred)

        print(f'{name}---confusion_matrix---')
        print(f' {matrix}')
        print(f'{name}---classification_report---')
        print(f"{report}\n")

In [104]:
preprocessor_01=make_pipeline(KNNImputer(n_neighbors=3),StandardScaler())
preprocessor_02=make_pipeline(KNNImputer(n_neighbors=3),RobustScaler())
preprocessor_03=make_pipeline(KNNImputer(n_neighbors=3),MinMaxScaler())

In [107]:
print("=============== StandardScaler================")
model_performance(preprocessor_01,X_train,X_test,Y_train,Y_test)

=============== StandardScaler================
DecisionTreeClassifier---confusion_matrix---
 [[3 0 0 0]
 [0 4 0 0]
 [0 0 4 0]
 [0 0 0 4]]
DecisionTreeClassifier---classification_report---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         4

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15


GaussianNB---confusion_matrix---
 [[3 0 0 0]
 [1 3 0 0]
 [0 0 3 1]
 [0 0 0 4]]
GaussianNB---classification_report---
              precision    recall  f1-score   support

           0       0.75      1.00      0.86         3
           1       1.00      0.75      0.86         4
           2       1.00      0.75      0.86         4
           3       0.80      1.00      0.8

c:\Users\sumen\anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sumen\anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sumen\anaconda3\envs\myenv\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sumen\anacond

KNeighborsClassifier---confusion_matrix---
 [[0 3 0 0]
 [0 4 0 0]
 [0 4 0 0]
 [0 4 0 0]]
KNeighborsClassifier---classification_report---
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.27      1.00      0.42         4
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00         4

    accuracy                           0.27        15
   macro avg       0.07      0.25      0.11        15
weighted avg       0.07      0.27      0.11        15


RidgeClassifier---confusion_matrix---
 [[2 1 0 0]
 [0 4 0 0]
 [0 0 4 0]
 [0 0 0 4]]
RidgeClassifier---classification_report---
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.80      1.00      0.89         4
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         4

    accuracy                

# Hyperparameter tunning

In [108]:
#Even the  DecisionTreeClassifier did the best among all,it seems to be like overfitted so,we will take other model with moderate accuracy
#we will go with random foresr classifier and now we will finetune that model

In [109]:
from sklearn.model_selection import GridSearchCV

In [113]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

In [114]:
rf_classifier = RandomForestClassifier()
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)

# Perform the grid search and fitting on every possible configuration
grid_search.fit(X_train, Y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [10, 20],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 200]},
             verbose=2)

In [115]:
print("Best hyperparameters:", grid_search.best_params_)

Best hyperparameters: {'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 50}


In [116]:
print("Best score:", grid_search.best_score_)

Best score: 0.95


In [117]:
import pickle
with open('model.pkl', 'wb') as f:
    pickle.dump(grid_search, f)
